### ISSUE TITLE
can you please publish the PKGBUILD on AUR ?

### ISSUE THREAD

**Issue by cyrinux** [PaddiM8/asahi-battery-threshold#1]
and thanks you for the work :)

**Comment by PaddiM8** [comment]
Yeah, done! https://aur.archlinux.org/packages/asahi-battery-threshold-git

**Comment by cyrinux** [comment]
@PaddiM8 thanks, but can you also add as `makedepends` git ? Good reflex generally for git based package, this help for those like me who build from chroot 😉  https://github.com/PaddiM8/asahi-battery-threshold/pull/2
